# Usar a imagem do java
FROM openjdk:21-jdk

# Copiar o JAR para dentro do container
COPY ./conexao-banco-de-dados-1.0-SNAPSHOT-jar-with-dependencies.jar /app/elt-app.jar

# Definir as variveis de ambiente
ENV MYSQL_URL=enderecoBanco
ENV MYSQL_USERNAME=usarioBanco
ENV MYSQL_PASSWORD=senhaUsuarioBanco
ENV MYSQL_CLASS_NAME=classNameBanco
ENV SLACK_URL=urlSlack

# Definindo inicialização do java com o container
ENTRYPOINT ["java", "-jar", "/app/elt-app.jar"]
