services:
	mysql:
		container_name: ContainerBanco
		image: imagem-bancoimmuno:latest
		restart: always
		environment:
      ENV MYSQL_ROOT_PASSWORD=urubu100
      ENV MYSQL_DATABASE=immunodata
      ENV MYSQL_USER=immuno
      ENV MYSQL_PASSWORD=urubu100@
	  volumes: 
      - mysql_data:/var/lib/mysql
      - ./init-scripts:/docker-entrypoint-initdb.d
	  ports:
		  - "3306:3306"

  web: 
    containet_name: ContainerSite
    imagem: imagem-siteimmuno:latest
    restart: always
	ports:
		  - "80:80"

volumes:
	mysql_data: