services:
  mysql:
    container_name: ContainerBanco
    image: fabiamdamaceno/projeto-pi-2o-semestre:banco-latest
    restart: always
#    volumes:
#      - mysql_data:/var/lib/mysql
#      - ./init-scripts:/docker-entrypoint-initdb.d
    ports:
      - "3306:3306"

  web:
    container_name: ContainerSite
    image: fabiamdamaceno/projeto-pi-2o-semestre:site-latest
    restart: always
    ports:
      - "80:80"

  javaapp:
    container_name: ContainerJava
    image: fabiamdamaceno/projeto-pi-2o-semestre:java-latest
    restart: no

#volumes:
#  mysql_data:
