# Usar a imagem do nodeJs 
FROM node:22

COPY ./config.txt /app/ 
 
# Definir o diretorio de trabalho onde o repositorio sera clonado 
WORKDIR /app

# Instalar git 
RUN apt-get update && apt-get install -y git 

# Clonar o repositorio do GitHub 
RUN git clone https://github.com/cynthiaangi/projeto-pi-2o-semestre.git 

# Definindo o diretorio de trabalho dentro do repo 
WORKDIR /app/projeto-pi-2o-semestre/site 

# Instalando as dependencias 
RUN npm install 

RUN npm install express 

# Expondo a porta do site 
EXPOSE 80

# Mudando configurações de ambiente do site 
RUN cat ../../config.txt > ./.env.dev 

# Iniciar o site
CMD ["npm", "start"]

