# Buscando imagem base mysql
FROM mysql:9.3.0

# Definindo configurações de ambiente
ENV MYSQL_ROOT_PASSWORD=urubu100
ENV MYSQL_DATABASE=immunodata
ENV MYSQL_USER=immuno
ENV MYSQL_PASSWORD=urubu100@

# Expondo porta MySQL
EXPOSE 3306

# Rodando script mysql das tabelas
COPY ./arquivos_sql-immunodata/script-immunodata.sql /docker-entrypoint-initdb.d/
