# Buscando imagem base mysql
FROM mysql:8.0

# Definindo configurações de ambiente
ENV MYSQL_ROOT_PASSWORD=senhaRoot
ENV MYSQL_DATABASE=baseDeDados
ENV MYSQL_USER=usuario
ENV MYSQL_PASSWORD=senhaUsuario

# Expondo porta MySQL
EXPOSE 3306

# Rodando script mysql das tabelas
COPY ./arquivos_sql-immunodata/script-immunodata.sql /docker-entrypoint-initdb.d/
